// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod org {

extern crate alloc;
#[allow(unused_imports, dead_code)]
pub mod cdsframework {

extern crate alloc;
#[allow(unused_imports, dead_code)]
pub mod ice {

extern crate alloc;
#[allow(unused_imports, dead_code)]
pub mod flatbuf {

extern crate alloc;

pub enum DoseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Dose<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Dose<'a> {
  type Inner = Dose<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Dose<'a> {
  pub const VT_DATE: ::flatbuffers::VOffsetT = 4;
  pub const VT_CVX: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Dose { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DoseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Dose<'bldr>> {
    let mut builder = DoseBuilder::new(_fbb);
    if let Some(x) = args.cvx { builder.add_cvx(x); }
    if let Some(x) = args.date { builder.add_date(x); }
    builder.finish()
  }


  #[inline]
  pub fn date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Dose::VT_DATE, None)}
  }
  #[inline]
  pub fn cvx(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Dose::VT_CVX, None)}
  }
}

impl ::flatbuffers::Verifiable for Dose<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("date", Self::VT_DATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("cvx", Self::VT_CVX, false)?
     .finish();
    Ok(())
  }
}
pub struct DoseArgs<'a> {
    pub date: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub cvx: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DoseArgs<'a> {
  #[inline]
  fn default() -> Self {
    DoseArgs {
      date: None,
      cvx: None,
    }
  }
}

pub struct DoseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DoseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_date(&mut self, date: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Dose::VT_DATE, date);
  }
  #[inline]
  pub fn add_cvx(&mut self, cvx: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Dose::VT_CVX, cvx);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DoseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DoseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Dose<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Dose<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Dose");
      ds.field("date", &self.date());
      ds.field("cvx", &self.cvx());
      ds.finish()
  }
}
pub enum PatientOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Patient<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Patient<'a> {
  type Inner = Patient<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Patient<'a> {
  pub const VT_BIRTH_DATE: ::flatbuffers::VOffsetT = 4;
  pub const VT_GENDER: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Patient { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PatientArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Patient<'bldr>> {
    let mut builder = PatientBuilder::new(_fbb);
    if let Some(x) = args.gender { builder.add_gender(x); }
    if let Some(x) = args.birth_date { builder.add_birth_date(x); }
    builder.finish()
  }


  #[inline]
  pub fn birth_date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Patient::VT_BIRTH_DATE, None)}
  }
  #[inline]
  pub fn gender(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Patient::VT_GENDER, None)}
  }
}

impl ::flatbuffers::Verifiable for Patient<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("birth_date", Self::VT_BIRTH_DATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("gender", Self::VT_GENDER, false)?
     .finish();
    Ok(())
  }
}
pub struct PatientArgs<'a> {
    pub birth_date: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub gender: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PatientArgs<'a> {
  #[inline]
  fn default() -> Self {
    PatientArgs {
      birth_date: None,
      gender: None,
    }
  }
}

pub struct PatientBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PatientBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_birth_date(&mut self, birth_date: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Patient::VT_BIRTH_DATE, birth_date);
  }
  #[inline]
  pub fn add_gender(&mut self, gender: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Patient::VT_GENDER, gender);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PatientBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PatientBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Patient<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Patient<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Patient");
      ds.field("birth_date", &self.birth_date());
      ds.field("gender", &self.gender());
      ds.finish()
  }
}
pub enum PatientRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PatientRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PatientRequest<'a> {
  type Inner = PatientRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PatientRequest<'a> {
  pub const VT_PATIENT: ::flatbuffers::VOffsetT = 4;
  pub const VT_HISTORY: ::flatbuffers::VOffsetT = 6;
  pub const VT_EXECUTION_DATE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PatientRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PatientRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PatientRequest<'bldr>> {
    let mut builder = PatientRequestBuilder::new(_fbb);
    if let Some(x) = args.execution_date { builder.add_execution_date(x); }
    if let Some(x) = args.history { builder.add_history(x); }
    if let Some(x) = args.patient { builder.add_patient(x); }
    builder.finish()
  }


  #[inline]
  pub fn patient(&self) -> Option<Patient<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Patient>>(PatientRequest::VT_PATIENT, None)}
  }
  #[inline]
  pub fn history(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Dose<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Dose>>>>(PatientRequest::VT_HISTORY, None)}
  }
  #[inline]
  pub fn execution_date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PatientRequest::VT_EXECUTION_DATE, None)}
  }
}

impl ::flatbuffers::Verifiable for PatientRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Patient>>("patient", Self::VT_PATIENT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Dose>>>>("history", Self::VT_HISTORY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("execution_date", Self::VT_EXECUTION_DATE, false)?
     .finish();
    Ok(())
  }
}
pub struct PatientRequestArgs<'a> {
    pub patient: Option<::flatbuffers::WIPOffset<Patient<'a>>>,
    pub history: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Dose<'a>>>>>,
    pub execution_date: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PatientRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    PatientRequestArgs {
      patient: None,
      history: None,
      execution_date: None,
    }
  }
}

pub struct PatientRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PatientRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_patient(&mut self, patient: ::flatbuffers::WIPOffset<Patient<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Patient>>(PatientRequest::VT_PATIENT, patient);
  }
  #[inline]
  pub fn add_history(&mut self, history: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Dose<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PatientRequest::VT_HISTORY, history);
  }
  #[inline]
  pub fn add_execution_date(&mut self, execution_date: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PatientRequest::VT_EXECUTION_DATE, execution_date);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PatientRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PatientRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PatientRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PatientRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PatientRequest");
      ds.field("patient", &self.patient());
      ds.field("history", &self.history());
      ds.field("execution_date", &self.execution_date());
      ds.finish()
  }
}
pub enum BulkForecastRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BulkForecastRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for BulkForecastRequest<'a> {
  type Inner = BulkForecastRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> BulkForecastRequest<'a> {
  pub const VT_REQUESTS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    BulkForecastRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BulkForecastRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<BulkForecastRequest<'bldr>> {
    let mut builder = BulkForecastRequestBuilder::new(_fbb);
    if let Some(x) = args.requests { builder.add_requests(x); }
    builder.finish()
  }


  #[inline]
  pub fn requests(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PatientRequest<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PatientRequest>>>>(BulkForecastRequest::VT_REQUESTS, None)}
  }
}

impl ::flatbuffers::Verifiable for BulkForecastRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<PatientRequest>>>>("requests", Self::VT_REQUESTS, false)?
     .finish();
    Ok(())
  }
}
pub struct BulkForecastRequestArgs<'a> {
    pub requests: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PatientRequest<'a>>>>>,
}
impl<'a> Default for BulkForecastRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    BulkForecastRequestArgs {
      requests: None,
    }
  }
}

pub struct BulkForecastRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BulkForecastRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_requests(&mut self, requests: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<PatientRequest<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(BulkForecastRequest::VT_REQUESTS, requests);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BulkForecastRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BulkForecastRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<BulkForecastRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for BulkForecastRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("BulkForecastRequest");
      ds.field("requests", &self.requests());
      ds.finish()
  }
}
pub enum SeriesForecastOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SeriesForecast<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SeriesForecast<'a> {
  type Inner = SeriesForecast<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SeriesForecast<'a> {
  pub const VT_SERIES_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_EARLIEST_DATE: ::flatbuffers::VOffsetT = 6;
  pub const VT_RECOMMENDED_DATE: ::flatbuffers::VOffsetT = 8;
  pub const VT_OVERDUE_DATE: ::flatbuffers::VOffsetT = 10;
  pub const VT_LATEST_DATE: ::flatbuffers::VOffsetT = 12;
  pub const VT_STATUS: ::flatbuffers::VOffsetT = 14;
  pub const VT_REASONS: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SeriesForecast { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SeriesForecastArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SeriesForecast<'bldr>> {
    let mut builder = SeriesForecastBuilder::new(_fbb);
    if let Some(x) = args.reasons { builder.add_reasons(x); }
    if let Some(x) = args.status { builder.add_status(x); }
    if let Some(x) = args.latest_date { builder.add_latest_date(x); }
    if let Some(x) = args.overdue_date { builder.add_overdue_date(x); }
    if let Some(x) = args.recommended_date { builder.add_recommended_date(x); }
    if let Some(x) = args.earliest_date { builder.add_earliest_date(x); }
    if let Some(x) = args.series_name { builder.add_series_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn series_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SeriesForecast::VT_SERIES_NAME, None)}
  }
  #[inline]
  pub fn earliest_date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SeriesForecast::VT_EARLIEST_DATE, None)}
  }
  #[inline]
  pub fn recommended_date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SeriesForecast::VT_RECOMMENDED_DATE, None)}
  }
  #[inline]
  pub fn overdue_date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SeriesForecast::VT_OVERDUE_DATE, None)}
  }
  #[inline]
  pub fn latest_date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SeriesForecast::VT_LATEST_DATE, None)}
  }
  #[inline]
  pub fn status(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SeriesForecast::VT_STATUS, None)}
  }
  #[inline]
  pub fn reasons(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(SeriesForecast::VT_REASONS, None)}
  }
}

impl ::flatbuffers::Verifiable for SeriesForecast<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("series_name", Self::VT_SERIES_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("earliest_date", Self::VT_EARLIEST_DATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("recommended_date", Self::VT_RECOMMENDED_DATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("overdue_date", Self::VT_OVERDUE_DATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("latest_date", Self::VT_LATEST_DATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("status", Self::VT_STATUS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("reasons", Self::VT_REASONS, false)?
     .finish();
    Ok(())
  }
}
pub struct SeriesForecastArgs<'a> {
    pub series_name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub earliest_date: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub recommended_date: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub overdue_date: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub latest_date: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub status: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub reasons: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
}
impl<'a> Default for SeriesForecastArgs<'a> {
  #[inline]
  fn default() -> Self {
    SeriesForecastArgs {
      series_name: None,
      earliest_date: None,
      recommended_date: None,
      overdue_date: None,
      latest_date: None,
      status: None,
      reasons: None,
    }
  }
}

pub struct SeriesForecastBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SeriesForecastBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_series_name(&mut self, series_name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SeriesForecast::VT_SERIES_NAME, series_name);
  }
  #[inline]
  pub fn add_earliest_date(&mut self, earliest_date: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SeriesForecast::VT_EARLIEST_DATE, earliest_date);
  }
  #[inline]
  pub fn add_recommended_date(&mut self, recommended_date: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SeriesForecast::VT_RECOMMENDED_DATE, recommended_date);
  }
  #[inline]
  pub fn add_overdue_date(&mut self, overdue_date: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SeriesForecast::VT_OVERDUE_DATE, overdue_date);
  }
  #[inline]
  pub fn add_latest_date(&mut self, latest_date: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SeriesForecast::VT_LATEST_DATE, latest_date);
  }
  #[inline]
  pub fn add_status(&mut self, status: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SeriesForecast::VT_STATUS, status);
  }
  #[inline]
  pub fn add_reasons(&mut self, reasons: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SeriesForecast::VT_REASONS, reasons);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SeriesForecastBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SeriesForecastBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SeriesForecast<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SeriesForecast<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SeriesForecast");
      ds.field("series_name", &self.series_name());
      ds.field("earliest_date", &self.earliest_date());
      ds.field("recommended_date", &self.recommended_date());
      ds.field("overdue_date", &self.overdue_date());
      ds.field("latest_date", &self.latest_date());
      ds.field("status", &self.status());
      ds.field("reasons", &self.reasons());
      ds.finish()
  }
}
pub enum DoseEvaluationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DoseEvaluation<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DoseEvaluation<'a> {
  type Inner = DoseEvaluation<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DoseEvaluation<'a> {
  pub const VT_DOSE_DATE: ::flatbuffers::VOffsetT = 4;
  pub const VT_CVX: ::flatbuffers::VOffsetT = 6;
  pub const VT_STATUS: ::flatbuffers::VOffsetT = 8;
  pub const VT_REASONS: ::flatbuffers::VOffsetT = 10;
  pub const VT_DOSE_NUMBER: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DoseEvaluation { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DoseEvaluationArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DoseEvaluation<'bldr>> {
    let mut builder = DoseEvaluationBuilder::new(_fbb);
    builder.add_dose_number(args.dose_number);
    if let Some(x) = args.reasons { builder.add_reasons(x); }
    if let Some(x) = args.status { builder.add_status(x); }
    if let Some(x) = args.cvx { builder.add_cvx(x); }
    if let Some(x) = args.dose_date { builder.add_dose_date(x); }
    builder.finish()
  }


  #[inline]
  pub fn dose_date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DoseEvaluation::VT_DOSE_DATE, None)}
  }
  #[inline]
  pub fn cvx(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DoseEvaluation::VT_CVX, None)}
  }
  #[inline]
  pub fn status(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DoseEvaluation::VT_STATUS, None)}
  }
  #[inline]
  pub fn reasons(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(DoseEvaluation::VT_REASONS, None)}
  }
  #[inline]
  pub fn dose_number(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(DoseEvaluation::VT_DOSE_NUMBER, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for DoseEvaluation<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("dose_date", Self::VT_DOSE_DATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("cvx", Self::VT_CVX, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("status", Self::VT_STATUS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("reasons", Self::VT_REASONS, false)?
     .visit_field::<i32>("dose_number", Self::VT_DOSE_NUMBER, false)?
     .finish();
    Ok(())
  }
}
pub struct DoseEvaluationArgs<'a> {
    pub dose_date: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub cvx: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub status: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub reasons: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub dose_number: i32,
}
impl<'a> Default for DoseEvaluationArgs<'a> {
  #[inline]
  fn default() -> Self {
    DoseEvaluationArgs {
      dose_date: None,
      cvx: None,
      status: None,
      reasons: None,
      dose_number: 0,
    }
  }
}

pub struct DoseEvaluationBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DoseEvaluationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_dose_date(&mut self, dose_date: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DoseEvaluation::VT_DOSE_DATE, dose_date);
  }
  #[inline]
  pub fn add_cvx(&mut self, cvx: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DoseEvaluation::VT_CVX, cvx);
  }
  #[inline]
  pub fn add_status(&mut self, status: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DoseEvaluation::VT_STATUS, status);
  }
  #[inline]
  pub fn add_reasons(&mut self, reasons: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DoseEvaluation::VT_REASONS, reasons);
  }
  #[inline]
  pub fn add_dose_number(&mut self, dose_number: i32) {
    self.fbb_.push_slot::<i32>(DoseEvaluation::VT_DOSE_NUMBER, dose_number, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DoseEvaluationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DoseEvaluationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DoseEvaluation<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DoseEvaluation<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DoseEvaluation");
      ds.field("dose_date", &self.dose_date());
      ds.field("cvx", &self.cvx());
      ds.field("status", &self.status());
      ds.field("reasons", &self.reasons());
      ds.field("dose_number", &self.dose_number());
      ds.finish()
  }
}
pub enum VaccineGroupForecastOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct VaccineGroupForecast<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for VaccineGroupForecast<'a> {
  type Inner = VaccineGroupForecast<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> VaccineGroupForecast<'a> {
  pub const VT_VACCINE_GROUP: ::flatbuffers::VOffsetT = 4;
  pub const VT_EVALUATIONS: ::flatbuffers::VOffsetT = 6;
  pub const VT_FORECASTS: ::flatbuffers::VOffsetT = 8;
  pub const VT_SELECTED_SERIES: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    VaccineGroupForecast { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args VaccineGroupForecastArgs<'args>
  ) -> ::flatbuffers::WIPOffset<VaccineGroupForecast<'bldr>> {
    let mut builder = VaccineGroupForecastBuilder::new(_fbb);
    if let Some(x) = args.selected_series { builder.add_selected_series(x); }
    if let Some(x) = args.forecasts { builder.add_forecasts(x); }
    if let Some(x) = args.evaluations { builder.add_evaluations(x); }
    if let Some(x) = args.vaccine_group { builder.add_vaccine_group(x); }
    builder.finish()
  }


  #[inline]
  pub fn vaccine_group(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(VaccineGroupForecast::VT_VACCINE_GROUP, None)}
  }
  #[inline]
  pub fn evaluations(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DoseEvaluation<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DoseEvaluation>>>>(VaccineGroupForecast::VT_EVALUATIONS, None)}
  }
  #[inline]
  pub fn forecasts(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<SeriesForecast<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<SeriesForecast>>>>(VaccineGroupForecast::VT_FORECASTS, None)}
  }
  #[inline]
  pub fn selected_series(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(VaccineGroupForecast::VT_SELECTED_SERIES, None)}
  }
}

impl ::flatbuffers::Verifiable for VaccineGroupForecast<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("vaccine_group", Self::VT_VACCINE_GROUP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<DoseEvaluation>>>>("evaluations", Self::VT_EVALUATIONS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<SeriesForecast>>>>("forecasts", Self::VT_FORECASTS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("selected_series", Self::VT_SELECTED_SERIES, false)?
     .finish();
    Ok(())
  }
}
pub struct VaccineGroupForecastArgs<'a> {
    pub vaccine_group: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub evaluations: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DoseEvaluation<'a>>>>>,
    pub forecasts: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<SeriesForecast<'a>>>>>,
    pub selected_series: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for VaccineGroupForecastArgs<'a> {
  #[inline]
  fn default() -> Self {
    VaccineGroupForecastArgs {
      vaccine_group: None,
      evaluations: None,
      forecasts: None,
      selected_series: None,
    }
  }
}

pub struct VaccineGroupForecastBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> VaccineGroupForecastBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_vaccine_group(&mut self, vaccine_group: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(VaccineGroupForecast::VT_VACCINE_GROUP, vaccine_group);
  }
  #[inline]
  pub fn add_evaluations(&mut self, evaluations: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<DoseEvaluation<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(VaccineGroupForecast::VT_EVALUATIONS, evaluations);
  }
  #[inline]
  pub fn add_forecasts(&mut self, forecasts: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<SeriesForecast<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(VaccineGroupForecast::VT_FORECASTS, forecasts);
  }
  #[inline]
  pub fn add_selected_series(&mut self, selected_series: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(VaccineGroupForecast::VT_SELECTED_SERIES, selected_series);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> VaccineGroupForecastBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    VaccineGroupForecastBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<VaccineGroupForecast<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for VaccineGroupForecast<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("VaccineGroupForecast");
      ds.field("vaccine_group", &self.vaccine_group());
      ds.field("evaluations", &self.evaluations());
      ds.field("forecasts", &self.forecasts());
      ds.field("selected_series", &self.selected_series());
      ds.finish()
  }
}
pub enum ForecastResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ForecastResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ForecastResponse<'a> {
  type Inner = ForecastResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ForecastResponse<'a> {
  pub const VT_VACCINE_GROUPS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ForecastResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ForecastResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ForecastResponse<'bldr>> {
    let mut builder = ForecastResponseBuilder::new(_fbb);
    if let Some(x) = args.vaccine_groups { builder.add_vaccine_groups(x); }
    builder.finish()
  }


  #[inline]
  pub fn vaccine_groups(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<VaccineGroupForecast<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<VaccineGroupForecast>>>>(ForecastResponse::VT_VACCINE_GROUPS, None)}
  }
}

impl ::flatbuffers::Verifiable for ForecastResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<VaccineGroupForecast>>>>("vaccine_groups", Self::VT_VACCINE_GROUPS, false)?
     .finish();
    Ok(())
  }
}
pub struct ForecastResponseArgs<'a> {
    pub vaccine_groups: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<VaccineGroupForecast<'a>>>>>,
}
impl<'a> Default for ForecastResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    ForecastResponseArgs {
      vaccine_groups: None,
    }
  }
}

pub struct ForecastResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ForecastResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_vaccine_groups(&mut self, vaccine_groups: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<VaccineGroupForecast<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ForecastResponse::VT_VACCINE_GROUPS, vaccine_groups);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ForecastResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ForecastResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ForecastResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ForecastResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ForecastResponse");
      ds.field("vaccine_groups", &self.vaccine_groups());
      ds.finish()
  }
}
pub enum BulkForecastResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BulkForecastResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for BulkForecastResponse<'a> {
  type Inner = BulkForecastResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> BulkForecastResponse<'a> {
  pub const VT_RESPONSES: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    BulkForecastResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BulkForecastResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<BulkForecastResponse<'bldr>> {
    let mut builder = BulkForecastResponseBuilder::new(_fbb);
    if let Some(x) = args.responses { builder.add_responses(x); }
    builder.finish()
  }


  #[inline]
  pub fn responses(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ForecastResponse<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ForecastResponse>>>>(BulkForecastResponse::VT_RESPONSES, None)}
  }
}

impl ::flatbuffers::Verifiable for BulkForecastResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ForecastResponse>>>>("responses", Self::VT_RESPONSES, false)?
     .finish();
    Ok(())
  }
}
pub struct BulkForecastResponseArgs<'a> {
    pub responses: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ForecastResponse<'a>>>>>,
}
impl<'a> Default for BulkForecastResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    BulkForecastResponseArgs {
      responses: None,
    }
  }
}

pub struct BulkForecastResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BulkForecastResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_responses(&mut self, responses: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ForecastResponse<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(BulkForecastResponse::VT_RESPONSES, responses);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BulkForecastResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BulkForecastResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<BulkForecastResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for BulkForecastResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("BulkForecastResponse");
      ds.field("responses", &self.responses());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `BulkForecastResponse`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_bulk_forecast_response_unchecked`.
pub fn root_as_bulk_forecast_response(buf: &[u8]) -> Result<BulkForecastResponse<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<BulkForecastResponse>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `BulkForecastResponse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_bulk_forecast_response_unchecked`.
pub fn size_prefixed_root_as_bulk_forecast_response(buf: &[u8]) -> Result<BulkForecastResponse<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<BulkForecastResponse>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `BulkForecastResponse` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_bulk_forecast_response_unchecked`.
pub fn root_as_bulk_forecast_response_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<BulkForecastResponse<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<BulkForecastResponse<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `BulkForecastResponse` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_bulk_forecast_response_unchecked`.
pub fn size_prefixed_root_as_bulk_forecast_response_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<BulkForecastResponse<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<BulkForecastResponse<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a BulkForecastResponse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `BulkForecastResponse`.
pub unsafe fn root_as_bulk_forecast_response_unchecked(buf: &[u8]) -> BulkForecastResponse<'_> {
  unsafe { ::flatbuffers::root_unchecked::<BulkForecastResponse>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed BulkForecastResponse and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `BulkForecastResponse`.
pub unsafe fn size_prefixed_root_as_bulk_forecast_response_unchecked(buf: &[u8]) -> BulkForecastResponse<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<BulkForecastResponse>(buf) }
}
#[inline]
pub fn finish_bulk_forecast_response_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<BulkForecastResponse<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_bulk_forecast_response_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<BulkForecastResponse<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod flatbuf
}  // pub mod ice
}  // pub mod cdsframework
}  // pub mod org

